### ISSUE TITLE
Vizdoom Portable Generator generates incorrect number of testing & training episodes, trials

### ISSUE THREAD

**Issue by cudy789** [holderlb/WSU-SAILON-NG#1]
Specifying the number of testing episodes and trials seems to have no effect on how many testing episodes/trials the Python TA2 is served. The following TA1 config file specifies 1 trial with 1 training and 0 testing episodes

```
[amqp]
user = (redacted)
pass = (redacted)
host = (redacted)
port = 49191
ssl = False

[postgresql]
user = aiq_user
pass = (redacted)
host = (redacted)
port = 59965
database = aiq_data

[sota]
username = username
secret = secret

[sail-on]
trials = 1
novelty = 200,101,102,103,104,105
difficulty = easy,medium,hard
normal_timeout_seconds = 600
training_timeout_multiplier = 10
testing_novelty_p2 = 1.0

[cartpole]
training_episodes = 20
testing_episodes = 20
pre_novel_episodes = 5
live = False
use_image = False

[vizdoom]
training_episodes = 1
testing_episodes = 0
pre_novel_episodes = 5
live = True
use_image = False

[smartenv]
training_episodes = 100
testing_episodes = 200
live = False

[options]
debug = False
fulldebug = False
printout = True
testing = False
demo = False
shortdemo = False
```

But the resulting games that the Python client gets served can be seen below from the agent's log file.

```
76:2021-09-01 09:13:37,649 - objects.TA2_logic.TA2 - INFO - Experiment Start
77:2021-09-01 09:13:37,667 - objects.TA2_logic.TA2 - INFO - Training Start
78:2021-09-01 09:13:37,712 - objects.TA2_logic.TA2 - INFO - Training Episode Start: #0
1761:2021-09-01 09:14:30,320 - objects.TA2_logic.TA2 - INFO - Training Episode Start: #1
5023:2021-09-01 09:15:56,479 - objects.TA2_logic.TA2 - INFO - Training Episode Start: #2
5623:2021-09-01 09:16:13,789 - objects.TA2_logic.TA2 - INFO - Starting the connection back up.
5625:2021-09-01 09:16:13,845 - objects.TA2_logic.TA2 - INFO - Trial Start: #0  novelty_desc: {}
5627:2021-09-01 09:16:13,855 - objects.TA2_logic.TA2 - INFO - Testing Start
5628:2021-09-01 09:16:13,893 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #0
7803:2021-09-01 09:17:01,574 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #1
9553:2021-09-01 09:17:49,990 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #2
11918:2021-09-01 09:20:13,290 - objects.TA2_logic.TA2 - INFO - Trial Start: #0  novelty_desc: {}
11920:2021-09-01 09:20:13,300 - objects.TA2_logic.TA2 - INFO - Testing Start
11921:2021-09-01 09:20:13,336 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #0
13464:2021-09-01 09:20:58,430 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #1
15756:2021-09-01 09:21:59,066 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #2
18135:2021-09-01 09:23:00,165 - objects.TA2_logic.TA2 - INFO - Trial Start: #0  novelty_desc: {}
18137:2021-09-01 09:23:00,176 - objects.TA2_logic.TA2 - INFO - Testing Start
18138:2021-09-01 09:23:00,216 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #0
20243:2021-09-01 09:24:26,839 - objects.TA2_logic.TA2 - INFO - Testing Episode Start: #1
```
Note that 3 training and 3 testing episodes each are served. More trials (with the same ID #) are served until we terminate the Python agent.

**Comment by cppbari** [comment]
The given config file will generate 36 trials.  Please read the documentation, there is no issue. [https://github.com/holderlb/WSU-SAILON-NG/tree/master/WSU-Portable-Generator#ta1configurationfile](https://github.com/holderlb/WSU-SAILON-NG/tree/master/WSU-Portable-Generator#ta1configurationfile)

**Comment by cudy789** [comment]
Thanks for getting back to me so quickly. I understand now why we were playing more than one trial, although it seems the trial ID should be incrementing by 1 after each trial, correct?

Regarding the number of training and testing episodes, the documentation you pointed me to seems to suggest that `training_episodes=1` `testing_episodes=0` should serve 1 training episode, then 0 testing episodes for 36 trials. As you can see from the log file, this is not the behavior our agent exhibits. Am I missing something here?

**Comment by cppbari** [comment]
The trial ID increments for each configuration, so if you have `trials=3` you would see it increment from 0 to 2 for each novelty/difficulty/visibility combination.

There is a minimum number of test episodes of 3 due to internal logic of the TA1 agent.

**Comment by cudy789** [comment]
Thanks for the clarification.
