### ISSUE TITLE
Requesting medium novelty causes server bug when running locally on latest

### ISSUE THREAD

**Issue by mmclure** [holderlb/WSU-SAILON-NG#6]
Not sure if this is expected (is medium difficulty supported for the mock novelties?).   I believe in a recent version it worked, or maybe it just quietly fell through to easy.  Anyway the stack trace is below for a test I tried to run (locally) on the latest with "medium" difficulty.  Interesting that the key error is on "easy".

Let me know if you need more data about the context.  Thanks!

ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m Traceback (most recent call last):
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "TA1.py", line 5304, in <module>
ESC[33mmmclure-vizdoom-rabbit       |ESC[0m 2021-11-09 05:57:36.454 [info] <0.947.0> accepting AMQP connection <0.947.0> ([::1]:41348 -> [::1]:51599)
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     service.start()
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "TA1.py", line 588, in start
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self.amqp.start_consuming()
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/aiq-sail-on/objects/rabbitmq.py", line 2014, in start_consuming
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self._channel.start_consuming()
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
ESC[33mmmclure-vizdoom-rabbit       |ESC[0m 2021-11-09 05:57:36.459 [info] <0.947.0> connection <0.947.0> ([::1]:41348 -> [::1]:51599): user 'bunny' authenticated and granted access to vhost '/'
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self._process_data_events(time_limit=None)
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self.connection.process_data_events(time_limit=time_limit)
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self._dispatch_channel_events()
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     impl_channel._get_cookie()._dispatch_events()
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1494, in _dispatch_events
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     evt.properties, evt.body)
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "/aiq-sail-on/objects/rabbitmq.py", line 147, in on_message
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     self.callback_function(channel, basic_deliver, properties, body, obj[0])
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "TA1.py", line 4661, in on_sail_on_request
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     errormsgs=errormsgs)
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m   File "TA1.py", line 4306, in prepare_episode
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m     episode.difficulty][episode.trial_novelty]['dataset_id']
ESC[32mmmclure-vizdoom-mockn-ta1    |ESC[0m KeyError: 'easy'

**Comment by cppbari** [comment]
Valid issue, some edge cases were missed when adding ability to select only certain difficulty levels.  Working on a fix now.

**Comment by cppbari** [comment]
This issue has been fixed in the latest commit.

**Comment by cppbari** [comment]
I was incorrect on the fix, digging further...

**Comment by cppbari** [comment]
Now it seems fixed.
